#!/usr/bin/env python
import time
import datetime
import sys
import csv
import os
import shutil
import subprocess
from scapy.utils import wrpcap
from mongol.probe import DnsWrongAnswerProbe
from mongol.probe import TcpRstProbe
from mongol.probe import TcpPacketDropProbe
from mongol.probe import UdpPacketDropProbe
from mongol import networking
from mongol import config

ALL_JAMMING_METHODS = set()
if config.dns_wrong_answer_probe:
    ALL_JAMMING_METHODS.add('DNS_WRONG_ANSWER')
if config.http_tcp_rst_probe:
    ALL_JAMMING_METHODS.add('HTTP_TCP_RST')
if config.dns_tcp_rst_probe:
    ALL_JAMMING_METHODS.add('DNS_TCP_RST')
if config.tcp_packet_drop_probe:
    ALL_JAMMING_METHODS.add('TCP_PACKET_DROP')
if config.udp_packet_drop_probe:
    ALL_JAMMING_METHODS.add('UDP_PACKET_DROP')

if len(sys.argv) == 1:
    print('[usage] ./find-router destination-ip')
    sys.exit(1)


def main(dst):
    if config.fixed_route:
        networking.make_route_fixed(config.fixed_route[0], config.fixed_route[1])
    iface, src, _ = networking.get_route(dst)
    if config.debug:
        print('probing between %s <=> %s, at interface %s' % (src, dst, iface))
    probed_at = datetime.datetime.now().isoformat()
    found_jamming_methods = set()
    for ttl in range(config.min_ttl, config.max_ttl + 1):
        more_jamming_methods = do_probing(probed_at, iface, src, dst, ttl, found_jamming_methods)
        found_jamming_methods = found_jamming_methods.union(more_jamming_methods)
        if ALL_JAMMING_METHODS == found_jamming_methods:
            break
    with open(os.path.join(config.output_dir, 'open-routes.csv'), 'a') as f:
        csv_writer = csv.writer(f)
        for missing_jamming_method in (ALL_JAMMING_METHODS - found_jamming_methods):
            csv_writer.writerow([probed_at, missing_jamming_method, dst])
    packets_dir = get_packets_dir(probed_at)
    if found_jamming_methods:
        subprocess.call('tar -zcf %s.tar.gz %s' % (packets_dir, packets_dir), shell=True)
    shutil.rmtree(packets_dir)


def get_packets_dir(probed_at):
    return os.path.join(config.output_dir, 'packets', probed_at)


def do_probing(probed_at, iface, src, dst, ttl, found_jamming_methods):
    if config.debug:
        print('')
        print('=== ttl: %s ===' % ttl)
    sniffer = networking.create_sniffer(iface, src, dst, config.sniffer_type)
    probes = {
        'UDP_ROUTE_PROBE_AA': UdpPacketDropProbe(
            src, config.udp_route_probe['a_sport'],
            dst, config.udp_route_probe['a_dport'],
            ttl, sniffer),
        'UDP_ROUTE_PROBE_AB': UdpPacketDropProbe(
            src, config.udp_route_probe['a_sport'],
            dst, config.udp_route_probe['b_dport'],
            ttl, sniffer),
        'UDP_ROUTE_PROBE_BA': UdpPacketDropProbe(
            src, config.udp_route_probe['b_sport'],
            dst, config.udp_route_probe['a_dport'],
            ttl, sniffer),
        'TCP_ROUTE_PROBE_AA': TcpPacketDropProbe(
            src, config.tcp_route_probe['a_sport'],
            dst, config.tcp_route_probe['a_dport'],
            ttl, sniffer),
        'TCP_ROUTE_PROBE_AB': TcpPacketDropProbe(
            src, config.tcp_route_probe['a_sport'],
            dst, config.tcp_route_probe['b_dport'],
            ttl, sniffer),
        'TCP_ROUTE_PROBE_BA': TcpPacketDropProbe(
            src, config.tcp_route_probe['b_sport'],
            dst, config.tcp_route_probe['a_dport'],
            ttl, sniffer)
    }
    if 'DNS_WRONG_ANSWER' not in found_jamming_methods and config.dns_wrong_answer_probe:
        probes['DNS_WRONG_ANSWER'] = DnsWrongAnswerProbe(
            src, config.dns_wrong_answer_probe['sport'],
            dst, config.dns_wrong_answer_probe['dport'], ttl, sniffer)
    if 'HTTP_TCP_RST' not in found_jamming_methods and config.http_tcp_rst_probe:
        probe_config = config.http_tcp_rst_probe
        probes['HTTP_TCP_RST'] = TcpRstProbe(
            src, probe_config['sport'],
            dst, probe_config['dport'], ttl, sniffer, offending_payload_type='HTTP',
            interval_between_syn_and_offending_payload=probe_config['interval_between_syn_and_http_get'])
    if 'DNS_TCP_RST' not in found_jamming_methods and config.dns_tcp_rst_probe:
        probe_config = config.dns_tcp_rst_probe
        probes['DNS_TCP_RST'] = TcpRstProbe(
            src, probe_config['sport'],
            dst, probe_config['dport'], ttl, sniffer, offending_payload_type='DNS',
            interval_between_syn_and_offending_payload=probe_config['interval_between_syn_and_dns_question'])
    if 'TCP_PACKET_DROP' not in found_jamming_methods and config.tcp_packet_drop_probe:
        probes['TCP_PACKET_DROP_BLOCKED'] = TcpPacketDropProbe(
            src, config.tcp_packet_drop_probe['blocked_sport'],
            dst, config.tcp_packet_drop_probe['blocked_dport'], ttl, sniffer)
        probes['TCP_PACKET_DROP_COMPARISON'] = TcpPacketDropProbe(
            src, config.tcp_packet_drop_probe['comparison_sport'],
            dst, config.tcp_packet_drop_probe['comparison_dport'], ttl, sniffer)
    if 'UDP_PACKET_DROP' not in found_jamming_methods and config.udp_packet_drop_probe:
        probes['UDP_PACKET_DROP_BLOCKED'] = UdpPacketDropProbe(
            src, config.udp_packet_drop_probe['blocked_sport'],
            dst, config.udp_packet_drop_probe['blocked_dport'], ttl, sniffer)
        probes['UDP_PACKET_DROP_COMPARISON'] = UdpPacketDropProbe(
            src, config.udp_packet_drop_probe['comparison_sport'],
            dst, config.udp_packet_drop_probe['comparison_dport'], ttl, sniffer)
    try:
        sniffer.start_sniffing()
        for probe in probes.values():
            probe.poke()
        time.sleep(config.interval_between_poke_and_peek)
        sniffer.stop_sniffing()
        for probe in probes.values():
            probe.peek()
    finally:
        for probe in probes.values():
            probe.close()
    dump_packets(probes)
    reports = {}
    for name, probe in probes.items():
        probe.report['PROBE_SPORT'] = probe.sport
        probe.report['PROBE_DPORT'] = probe.dport
        reports[name] = probe.report
    write_packets(get_packets_dir(probed_at), reports)
    jamming_events, udp_route_type, tcp_route_type = analyze_reports(reports)
    if not jamming_events:
        return set()
    with open(os.path.join(config.output_dir, 'gfw-attached-routers.csv'), 'a') as f:
        csv_writer = csv.writer(f)
        for jamming_method, router_ip in jamming_events.items():
            print('found jamming event: %s at %s (%s, %s)' %
                  (jamming_method, router_ip, udp_route_type, tcp_route_type))
            csv_writer.writerow([probed_at, jamming_method, dst, str(ttl), router_ip, udp_route_type, tcp_route_type])
    return set(jamming_events.keys())


def dump_packets(probes):
    if not config.debug:
        return
    for name, probe in probes.items():
        print('%s PROBE:' % name)
        for mark, packet in probe.report['PACKETS']:
            formatted_packet = packet.sprintf(
                '\t%.time% [' + mark + '] %IP.ttl% {TCP:%TCP.window% %TCP.flags%}{ICMP:%IP.src%}')
            print(formatted_packet)


def analyze_reports(reports):
    jamming_events = {}
    udp_route_type = get_route_type(
        reports['UDP_ROUTE_PROBE_AA'], reports['UDP_ROUTE_PROBE_AB'], reports['UDP_ROUTE_PROBE_BA'])
    tcp_route_type = get_route_type(
        reports['TCP_ROUTE_PROBE_AA'], reports['TCP_ROUTE_PROBE_AB'], reports['TCP_ROUTE_PROBE_BA'])
    router_ip = get_gfw_attached_router_ip_from_dns_wrong_answer_probe_report(reports.get('DNS_WRONG_ANSWER'))
    if router_ip:
        jamming_events['DNS_WRONG_ANSWER'] = router_ip
    router_ip = get_gfw_attached_router_ip_from_tcp_rst_probe_report(reports.get('HTTP_TCP_RST'))
    if router_ip:
        jamming_events['HTTP_TCP_RST'] = router_ip
    router_ip = get_gfw_attached_router_ip_from_tcp_rst_probe_report(reports.get('DNS_TCP_RST'))
    if router_ip:
        jamming_events['DNS_TCP_RST'] = router_ip
    router_ip = get_gfw_attached_router_ip_from_packet_drop_probe_report(
        reports.get('TCP_PACKET_DROP_BLOCKED'), reports.get('TCP_PACKET_DROP_COMPARISON'), tcp_route_type)
    if router_ip:
        jamming_events['TCP_PACKET_DROP'] = router_ip
    router_ip = get_gfw_attached_router_ip_from_packet_drop_probe_report(
        reports.get('UDP_PACKET_DROP_BLOCKED'), reports.get('UDP_PACKET_DROP_COMPARISON'), udp_route_type)
    if router_ip:
        jamming_events['UDP_PACKET_DROP'] = router_ip
    return jamming_events, 'UDP_%s' % udp_route_type, 'TCP_%s' % tcp_route_type


def get_route_type(report_aa, report_ab, report_ba):
    ip_aa = get_router_ip_found_by_packet_drop_probe_report(report_aa)
    ip_ab = get_router_ip_found_by_packet_drop_probe_report(report_ab)
    ip_ba = get_router_ip_found_by_packet_drop_probe_report(report_ba)
    if any([ip_aa is None, ip_ab is None, ip_ba is None]):
        return 'ROUTE_UNKNOWN'
    is_dport_dependent = ip_aa != ip_ab
    is_sport_dependent = ip_aa != ip_ba
    if is_dport_dependent and is_sport_dependent:
        return 'ROUTE_BOTH_DEPENDENT'
    if is_dport_dependent:
        return 'ROUTE_DPORT_DEPENDENT'
    if is_sport_dependent:
        return 'ROUTE_SPORT_DEPENDENT'
    return 'ROUTE_INDEPENDENT'


def write_packets(packets_dir, reports):
    if not os.path.exists(packets_dir):
        os.makedirs(packets_dir)
    for name, report in reports.items():
        packets = [packet for mark, packet in report['PACKETS']]
        wrpcap(os.path.join(packets_dir, name), packets, append=True)


def get_gfw_attached_router_ip_from_dns_wrong_answer_probe_report(report):
    if not report:
        return None
    if report['WRONG_ANSWER']:
        return report['ROUTER_IP'] or '*'
    return None


def get_gfw_attached_router_ip_from_tcp_rst_probe_report(report):
    if not report:
        return None
    if report['RST_AFTER_SYN?'] or report['RST_AFTER_OFFENDING_PAYLOAD?']:
        return report['ROUTER_IP_FOUND_BY_SYN'] or\
               report['ROUTER_IP_FOUND_BY_OFFENDING_PAYLOAD'] or '*'
    return None


def get_gfw_attached_router_ip_from_packet_drop_probe_report(report_blocked, report_comparison, route_type):
    if not report_blocked or not report_comparison:
        return None
    router_ip_blocked = get_router_ip_found_by_packet_drop_probe_report(report_blocked)
    router_ip_comparison = get_router_ip_found_by_packet_drop_probe_report(report_comparison)
    if not router_ip_blocked and router_ip_comparison:
        return router_ip_comparison if is_comparsion_router_ip_reliable(
            report_blocked, report_comparison, route_type) else '*'
    return None


def is_comparsion_router_ip_reliable(report_blocked, report_comparison, route_type):
    is_sport_different = report_blocked['PROBE_SPORT'] != report_comparison['PROBE_SPORT']
    is_dport_different = report_blocked['PROBE_DPORT'] != report_comparison['PROBE_DPORT']
    if is_dport_different and route_type in ['ROUTE_DPORT_DEPENDENT', 'ROUTE_BOTH_DEPENDENT']:
        return False
    if is_sport_different and route_type in ['ROUTE_SPORT_DEPENDENT', 'ROUTE_BOTH_DEPENDENT']:
        return False
    return True


def get_router_ip_found_by_packet_drop_probe_report(report):
    router_ip = report['ROUTER_IP_FOUND_BY_PACKET_1']
    router_ip = router_ip or report['ROUTER_IP_FOUND_BY_PACKET_2']
    router_ip = router_ip or report['ROUTER_IP_FOUND_BY_PACKET_3']
    return router_ip


main(*sys.argv[1:])